version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: adoptopenjdk:17-jre-hotspot
    volumes:
      - ./data:/data
    command: java -jar /data/h2-1.4.200.jar -web -webAllowOthers -tcp -tcpAllowOthers
    ports:
      - 8082:8082
    working_dir: /data
